#!/usr/bin/env bash
# This script transfers a file to a remote server using scp
if (($# < 3)); then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
elif (($# == 4)); then
    scp -i "$4" "$1" "$3"@"$2":~/
else
    scp "$1" "$3"@"$2":~/
fi
