#!/usr/bin/bash
# This script will print numbers from 1 to 20 and will print a message if the number is 4, 9 or 17

count=1

while [ $count -le 20 ]
do
  echo "$count"
  case $count in
    "4") echo "bad luck from China";;
    "9") echo "bad luck from Japan";;
    "17") echo "bad luck from Italy";;
  esac
  (( count++ ))
done
