#!/usr/bin/env bash
# Run nginx as the nginx user
chmod 644 /etc/nginx/nginx.conf
sed -Ei 's/\s*#?\s*user .*/user nginx;/' /etc/nginx/nginx.conf
sed -Ei 's/(listen (\[::\]:)?80) /\180 /' /etc/nginx/sites-available/default
pkill apache2
su nginx -s /bin/bash -c 'service nginx restart'
